FROM node:20-alpine

ENV VITE_API_URL=http://localhost:3000

WORKDIR /app

# Copy package files
COPY ./client/package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY ./client .

# Build the app
RUN npm run build

# Install serve globally
RUN npm install -g serve

# Expose default serve port
EXPOSE 5173

# Start serve to host the built files
CMD ["serve", "-s", "dist", "-l", "5173"]
